### PR TITLE
build: upgrade dep flutter_svg

### PR DESCRIPTION
**Pull request by JigneshPatel23**

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
Thanks for the contribution! Will merge it later and publish it 🚀

**Comment by erickok** [comment]
Could this even be `flutter_svg: '>=0.23.0+1 <2.0.0'` to not force 1.0.0 but still be compatible?

**Comment by creativecreatorormaybenot** [comment]
@erickok Is this indicated to be safe by the library? Usually this would not be possible because `1.0.0` is a breaking change.

**Comment by erickok** [comment]
Well, if they properly use semantic versioning everything below 2.0 should be non breaking from 1.0 onwards.

**Comment by erickok** [comment]
Or do you mean 0.23? 1.0 is just the stable release of 0.23

**Comment by creativecreatorormaybenot** [comment]
@erickok `1.0.0` should be breaking from `0.x.y`.

**Comment by erickok** [comment]
Except it is not - it is just making a stable release. Really it was only a suggestion and I wasn't even sure this is the best approach anyway. I was just trying to see if there is something we (I also work on several flutter libs) can do such that we don't need a new release every time some dependency updates.

**Comment by JEuler** [comment]
> Could this even be `flutter_svg: '>=0.23.0+1 <2.0.0'` to not force 1.0.0 but still be compatible?

I think it would be cool! I will create PR for flutter_html lib when this will be done :)

**Comment by creativecreatorormaybenot** [comment]
@erickok From the `flutter_svg` CHANGELOG:

> New widget/RenderObject implementation to avoid rebuilds/paints when near or overlapping an animating widget. Also should improve raster cacheability.

> Support for em/ex units.

So it is definitely not "just making a stable release". It might not be breaking, but I do not see an actual benefit in what you proposed.

The proper solution in my mind would be to bump `flutter_svg` to `1.0.0`, which means that `flutter_math_fork` **also** needs a breaking change (i.e. bumping the dependency) and therefore a new major version has to be released.  
This would be the correct way of handling this according to semantic versioning and I think it makes sense to be consistent about this.

**Comment by erickok** [comment]
Fair enough.

**Review by creativecreatorormaybenot — APPROVED** [review]

**Pull request merged**
